apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: vineshgoyal/micro_serv_post
      context: posts
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
    - image: vineshgoyal/micro_serv_comment
      context: comments
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
